FIND_PATH(MATHEVAL_INCLUDE_DIR matheval.h)

SET(MATHEVAL_NAMES ${MATHEVAL_NAMES} matheval)
FIND_LIBRARY(MATHEVAL_LIBRARY NAMES ${MATHEVAL_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set MATHEVAL_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MATHEVAL DEFAULT_MSG MATHEVAL_LIBRARY MATHEVAL_INCLUDE_DIR)

IF(MATHEVAL_FOUND)
    SET( MATHEVAL_LIBRARIES ${MATHEVAL_LIBRARY} )
ENDIF(MATHEVAL_FOUND)
